### PR TITLE
[PR] Extending README and refactoring project (2024)

### LINKED ISSUE #2: 2024 Comprehensive Update ⏳
@LuchoTurtle I explored `Next.js` https://nextjs.org/ as part of a previous project (2021) ⏳ 
looks like we might be needing a quick start for the framework again.  🏦 

Wanna pick this up and expand it to the level of: https://github.com/dwyl/learn-tailwind ? 🧑‍💻 💭

### PR DESCRIPTION
**Pull request by LuchoTurtle**
fixes #2 

This PR extends the current `README` with high-level topics regarding `Next.js 14` and creates a new project that is loosely based on the [official Learning Docs ](https://nextjs.org/learn?utm_source=next-site&utm_medium=navbar&utm_campaign=learn_dashboard-app) dashboard demo, but simplified and with higher emphasis on rendering and routing.

Because the official demo necessitates an account in `Vercel` and creating a database, this simplified version calls external free public APIs (https://picsum.photos and https://jsonplaceholder.typicode.com/) to populate the web app.

### CODE REVIEW

**Comment by nelsonic** [comment]
I've checked out your branch to `localhost` 💻  to run it on the plane ✈️ 🧑‍💻 
`npm install` taking a _looooong_ time ... ⏳ 🙃

**Comment by nelsonic** [comment]
```sh
added 578 packages, and audited 579 packages in 2m

172 packages are looking for funding
  run `npm fund` for details

3 vulnerabilities (1 moderate, 2 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
```

😕

**Comment by nelsonic** [comment]
ran:
```sh
npm start
```

Got the following error:
```
> start
> next start

   ▲ Next.js 14.0.2
   - Local:        http://localhost:3000

[Error: ENOENT: no such file or directory, open '/learn-nextjs/.next/BUILD_ID'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/learn-nextjs/.next/BUILD_ID'
}
```

But after running:
```sh
npm run build
```

with the result:
```sh
> build
> next build

Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

   ▲ Next.js 14.0.2

Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
 ✓ Creating an optimized production build
 ✓ Compiled successfully
 ✓ Linting and checking validity of types
 ✓ Collecting page data
   Generating static pages (0/6)  [    ]Fetching photos data...
Fetching photos data...
 ✓ Generating static pages (6/6)
 ✓ Collecting build traces
 ✓ Finalizing page optimization

Route (app)                              Size     First Load JS
┌ ○ /                                    175 B          91.4 kB
├ ○ /_not-found                          870 B          85.3 kB
├ ○ /dashboard                           5.18 kB        89.6 kB
├ λ /dashboard/posts                     2.78 kB          94 kB
└ λ /dashboard/posts/[id]                142 B          84.6 kB
+ First Load JS shared by all            84.4 kB
  ├ chunks/472-61f351621ba806f6.js       29.2 kB
  ├ chunks/fd9d1056-d1cf127711f3e2d5.js  53.3 kB
  ├ chunks/main-app-78d9598144742505.js  219 B
  └ chunks/webpack-0b9cfb2c486442dc.js   1.68 kB


○  (Static)   prerendered as static content
λ  (Dynamic)  server-rendered on demand using Node.js
```

The start command works:
```sh
npm start

> start
> next start

   ▲ Next.js 14.0.2
   - Local:        http://localhost:3000

 ✓ Ready in 188ms
```

http://localhost:3000
image

http://localhost:3000/dashboard
image

Appears to be responsive:
image

Looks good so far. 👌 
Will read the `README.md` offline. 👀 
But won't make any changes to not induce `merge-conflicts`. 👍

**Comment by nelsonic** [comment]
@LuchoTurtle assign when ready. 🙏 
We're going to be _using_ this very soon. ⏳

**Comment by LuchoTurtle** [comment]
image
already is
@nelsonic

**Comment by nelsonic** [comment]
Going to pick this up and finish tonight after work-work. 🧑‍💻 ⏳

**Comment by nelsonic** [comment]
We _really_ need tests in _everything_ we do. https://github.com/dwyl/learn-nextjs/issues/5
If it's difficult, ask for help. 

Going to do this today after work-work. ⌛

**Comment by nelsonic** [comment]
Basic test added. Just so we have _something_. 
But when viewing the /dashboard: 

nextjs-dashboard-click-posts

Clicking on the `/posts` gives us a `500` error:

image

# 😢 

Follow-up issue: https://github.com/dwyl/learn-nextjs/issues/6 👌

**Review by nelsonic — APPROVED** [review]
Thanks @LuchoTurtle ❤️

**Pull request merged**
